### ISSUE TITLE
Possibility of using centrifydc instead of sssd? 

### ISSUE THREAD

**Issue by joeydumont** [ComputeCanada/puppet-jupyterhub#17]
README.md says that `sssd` is required, but the only explicit dependence I see is in the `jupyter` service resource block. Do you think I could use `centrifydc` here instead? As far as I know, authentication still goes through PAM, this would just subcribe `jupyter` to another service.

**Comment by cmd-ntrf** [comment]
You are right. The only reference to SSSD is here:
https://github.com/ComputeCanada/puppet-jupyterhub/blob/master/manifests/init.pp#L195

I had to add a subscription to SSSD because in the context of [Magic Castle](https://www.github.com/computecanada/magic_castle), everything is installed from scratch, including the authentication modules and JupyterHub. Without the subscription, JupyterHub could be started before SSSD, and the authentication was not working.

You can remove the subscription to SSSD or replace it with the authentication daemon you used. I have not planned the module to do it, but if you report back a successful attempt, I will look into how to make that aspect of the module more general.

**Comment by joeydumont** [comment]
Sorry for not responding sooner, I still haven't had a chance to test it. I will comment on here if I do get the chance.

Thanks for the explanation!
